---
title: "Vis 1"
author: "Wenjie Wu"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggridges)
library(readxl)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making first plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Advanced scatterplot

```{r}
ggp_weather_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()

ggp_weather_scatterplot
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3, size = .8) + 
  geom_smooth(se = FALSE)
```

Where you define aesthetics can matter

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .3, size = .8) + 
  geom_smooth(se = FALSE)
```

Use faceting real quick

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + 
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

Interesting scatterplot

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) + 
  geom_point(alpha = .3) + 
  geom_smooth() + 
  facet_grid(. ~ name)
```

```{r}
weather_df_ny = weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax_fahr = tmax * (9/5) + 32,
    tmin_fahr = tmin * (9/5) + 32
  ) |>
    ggplot(aes(x = tmin_fahr, y = tmin_fahr)) + 
    geom_point(alpha = .3) + 
    geom_smooth(method = "lm", se = FALSE)
```


```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = "blue")) + 
  geom_point()
```

## Univariate plots

```{r}
weather_df |>
  ggplot(aes(x = tmin)) + 
  geom_histogram()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram(position = "dodge")
```

How to fix? Facet?

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram() + 
  facet_grid(. ~ name)
```

Density plot?

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_density(alpha = .3)
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin)) + 
  geom_boxplot()
```
Violin plots

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) + 
  geom_violin()
```

Ridge plot

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = name)) + 
  geom_density_ridges()
```

```{r}
weather_df |>
  filter(prcp > 10) |>
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .3)
```

## Saving and embedding plots

```{r}
ggp_weather = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, coYeslor = name)) + 
  geom_point()

ggsave("plots/ggp_weather.pdf", ggp_weather, width = 8, height = 6)
```

Embedding plots

```{r, fig.width = 12, fig.height = 12}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point()
```

